server:
  port: 8090
spring:
  data:
    mongodb:
      database: sc_sample
      host: localhost
      username: yepapa
      password: yepapa
      port: 27017
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://yepapa:yepapa@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    com.yejpapa: debug