server:
  port: 8765
spring:
  application:
    name: gateway-zuul
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://yepapa:yepapa@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  retryable: true
  routes:
    users:
      path: /user/**
      serviceId: user-service
  ribbon-isolation-strategy: thread
  strip-prefix: true

