spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yepapa/spring-cloud-config-repos.git

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://yepapa:yepapa@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS