spring:
  application:
    name: spring-boot-admin2

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://yepapa:yepapa@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS