spring:
  application:
    name: spring-boot-admin2
  boot:
    admin:
      ui:
        brand: "<img src=\"assets/img/icon-spring-boot-admin.svg\"><span>YeThree Boot Admin</span>"
        title: "YeThree Boot Admin"

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://yepapa:yepapa@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

