spring:
  application:
    name: spring-boot-admin2
  boot:
    admin:
      ui:
        brand: "<img src=\"assets/img/icon-spring-boot-admin.svg\"><span>YeThree Boot Admin</span>"
        title: "YeThree Boot Admin"

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://yepapa:yepapa@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#spring.boot.admin.ui.cache.no-cache: true
#spring.boot.admin.ui.extension-resource-locations: file:/data/workspace_oss/spring-boot-admin/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui/target/dist/
#spring.boot.admin.ui.cache-templates: false